export const chineseDishes = [
  {
    id: 1,
    name: "General Tso's Chicken",
    description:
      "General Tso's Chicken is a famous Chinese-American dish known for its sweet, tangy, and slightly spicy flavor. It features crispy chicken pieces coated in a flavorful sauce.",
    ingredients: [
      { name: "Chicken Thighs", quantity: "500g" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Rice Vinegar", quantity: "1 tbsp" },
      { name: "Sugar", quantity: "2 tbsp" },
      { name: "Cornstarch", quantity: "2 tbsp" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Ginger", quantity: "1-inch piece" },
      { name: "Dried Red Chilies", quantity: "6-8" },
      { name: "Sesame Oil", quantity: "1 tsp" },
      { name: "Green Onions", quantity: "2 stalks" },
      { name: "Cooking Oil", quantity: "3 cups" },
    ],
    image: "/images/genral tso's chicken.jpeg",
  },
  {
    id: 2,
    name: "Mongolian Beef",
    description:
      "Mongolian Beef is a classic Chinese stir-fry dish with tender strips of beef, scallions, and a savory brown sauce. It's simple yet incredibly flavorful.",
    ingredients: [
      { name: "Flank Steak", quantity: "400g" },
      { name: "Soy Sauce", quantity: "1/4 cup" },
      { name: "Brown Sugar", quantity: "1/4 cup" },
      { name: "Cornstarch", quantity: "2 tbsp" },
      { name: "Green Onions", quantity: "2 stalks" },
      { name: "Garlic", quantity: "4 cloves" },
      { name: "Ginger", quantity: "1-inch piece" },
      { name: "Sesame Oil", quantity: "1 tsp" },
      { name: "Cooking Oil", quantity: "2 tbsp" },
    ],
    image: "/images/mongolian-beef.jpg",
  },
  {
    id: 3,
    name: "Szechuan Shrimp",
    description:
      "Szechuan Shrimp is a spicy and flavorful Chinese dish made with plump shrimp, Szechuan peppercorns, and a savory sauce. It packs a bold and spicy punch.",
    ingredients: [
      { name: "Large Shrimp", quantity: "400g" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Hoisin Sauce", quantity: "2 tbsp" },
      { name: "Rice Vinegar", quantity: "1 tbsp" },
      { name: "Szechuan Peppercorns", quantity: "1 tsp" },
      { name: "Garlic", quantity: "4 cloves" },
      { name: "Ginger", quantity: "1-inch piece" },
      { name: "Green Onions", quantity: "2 stalks" },
      { name: "Sesame Oil", quantity: "1 tsp" },
      { name: "Cooking Oil", quantity: "2 tbsp" },
    ],
    image: "/images/Szechuan Shrimp.jpeg",
  },
  {
    id: 4,
    name: "Kung Pao Chicken",
    description:
      "Kung Pao Chicken is a popular Sichuan dish known for its bold and spicy flavors. Tender chicken is stir-fried with peanuts, Sichuan peppercorns, and dried red chilies, creating a perfect balance of heat and savory goodness.",
    ingredients: [
      { name: "Chicken", quantity: "300g" },
      { name: "Peanuts", quantity: "1/2 cup" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Vinegar", quantity: "1 tbsp" },
      { name: "Sugar", quantity: "1 tsp" },
      { name: "Sichuan Peppercorns", quantity: "1/2 tsp" },
      { name: "Dried Red Chilies", quantity: "4-5" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Ginger", quantity: "1-inch piece" },
      { name: "Scallions", quantity: "2 stalks" },
      { name: "Cooking Oil", quantity: "2 tbsp" },
    ],
    image: "/images/Kung-Pao-Chicken-Recipe3a.jpg",
  },
  {
    id: 5,
    name: "Fried Rice",
    description:
      "Fried Rice is a classic Chinese dish that's quick to make and bursting with flavor. Cooked rice is stir-fried with eggs, peas, carrots, and a savory soy sauce mixture, resulting in a delightful combination of textures and tastes.",
    ingredients: [
      { name: "Cooked Rice", quantity: "2 cups" },
      { name: "Eggs", quantity: "2" },
      { name: "Frozen Peas and Carrots", quantity: "1/2 cup" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Sesame Oil", quantity: "1 tsp" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Cooking Oil", quantity: "2 tbsp" },
    ],
    image: "/images/Fried-Rice-9-500x500.jpg",
  },
  {
    id: 6,
    name: "Hot and Sour Soup",
    description:
      "Hot and Sour Soup is a comforting Chinese soup that tantalizes your taste buds with its spicy and tangy flavors. It features chicken or tofu, mushrooms, bamboo shoots, and tofu in a flavorful broth, with a perfect balance of heat and sourness.",
    ingredients: [
      { name: "Chicken or Tofu", quantity: "200g" },
      { name: "Mushrooms", quantity: "1/2 cup" },
      { name: "Bamboo Shoots", quantity: "1/4 cup" },
      { name: "Tofu", quantity: "1/4 cup" },
      { name: "Egg", quantity: "1" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Vinegar", quantity: "2 tbsp" },
      { name: "Sesame Oil", quantity: "1 tsp" },
      { name: "Cornstarch", quantity: "1 tbsp" },
      { name: "Chili Paste", quantity: "1 tsp" },
      { name: "Chicken Broth", quantity: "4 cups" },
    ],
    image: "/images/Hot-and-sour-soup-recipe.jpg",
  },
];
